<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RepositoryGenerator.Generator\RepositoryGenerator.Generator.csproj" 
					  ReferenceOutputAssembly="false"
					  OutputItemType="Analyzer" />
    <ProjectReference Include="..\RepositoryGenerator.Library\RepositoryGenerator.Library.csproj" />
    <ProjectReference Include="..\RPDemo.Application\RPDemo.Application.csproj" />
    <ProjectReference Include="..\RPDemo.Domain\RPDemo.Domain.csproj" />
  </ItemGroup>

	<PropertyGroup>
		<ProduceReferenceAssembly>true</ProduceReferenceAssembly>
	</PropertyGroup>

</Project>
